export const elements = {
    idText: document.getElementById("IdDisplay"),
    callInput: document.getElementById("callInput"),
    callButton: document.getElementById("call-btn"),
    incomingCallDiv: document.getElementById("incoming-call"),
    incomingCallText: document.getElementById("incomingCaller"),
    incomingCallAcceptButton: document.getElementById("acceptCall"),
    incomingCallDeclineButton: document.getElementById("declineCall"),
    localVideoFullscreen: document.getElementById("local-video-idle"),
    localVideoDiv: document.getElementById("localVideoOnly"),
    localVideoPip: document.getElementById("local-video-pip"),
    localAndRemoteVideoDiv: document.getElementById("localAndRemoteVideo"),
    remoteVideo: document.getElementById("remote-video"),
    menu: document.getElementById('menu-btn'),
    mobileSettingsButton: document.getElementById('mobile-settings-btn'),
    cancelCallButton: document.getElementById('cancel-call-btn'),
    controlMute: document.getElementById('ctrl-mute'),
    controlCam: document.getElementById('ctrl-cam'),
    controlFlip: document.getElementById('ctrl-flip'),
    controlEnd: document.getElementById('ctrl-end'),
    controlSettings: document.getElementById('ctrl-settings'),
    incomingDecline: document.getElementById('inc-decline'),
    incomingAccept: document.getElementById('inc-accept'),
    closeSettings: document.getElementById('close-settings'),
    sidebar: document.getElementById('sidebar'),
    sidebarOvl   : document.getElementById('sidebar-overlay'),
    contactsList : document.getElementById('contacts-list'),
    searchInput  : document.getElementById('search-input'),
    idleScreen   : document.getElementById('idle-screen'),
    callingScr   : document.getElementById('calling-screen'),
    callScreen   : document.getElementById('call-screen'),
    callingAvatar: document.getElementById('calling-avatar'),
    callingName  : document.getElementById('calling-name'),
    remoteArea   : document.getElementById('remote-area'),
    localVideo   : document.getElementById('local-video'),
    pipWrap      : document.getElementById('pip-wrap'),
    pipNoCam     : document.getElementById('pip-no-cam'),
    infoName     : document.getElementById('info-name'),
    infoTimer    : document.getElementById('info-timer'),
    incomingEl   : document.getElementById('incoming-call'),
    incAvatar    : document.getElementById('inc-avatar'),
    incName      : document.getElementById('inc-name'),
    settingsPanel: document.getElementById('settings-panel'),
    addModal     : document.getElementById('add-modal'),
    mainIdleIn   : document.getElementById('idle-inner'),
    selectCamera : document.getElementById('sel-camera'),
    selectMic    : document.getElementById('sel-mic'),
    selectSpeaker : document.getElementById('sel-speaker'),
    addButton: document.getElementById('add-btn'),
    cancelModal: document.getElementById('modal-cancel'),
    confirmModal: document.getElementById('modal-confirm'),
    nameInput: document.getElementById('inp-name'),
    detailInput: document.getElementById('inp-detail'),
    settingsButton: document.getElementById('settings-btn'),
    toggleMirror: document.getElementById('toggle-mirror'),
    connectionInput: document.getElementById('inp-conn-id'),
    callModal     : document.getElementById('call-modal'),
    confirmCallButton     : document.getElementById('call-confirm'),
};
