export const elements = {
    idText: document.getElementById("IdDisplay"),
    callInput: document.getElementById("callInput"),
    callButton: document.getElementById("callButton"),
    incomingCallDiv: document.getElementById("incomingCall"),
    incomingCallText: document.getElementById("incomingCaller"),
    incomingCallAcceptButton: document.getElementById("acceptCall"),
    incomingCallDeclineButton: document.getElementById("declineCall"),
    localVideoFullscreen: document.getElementById("localVideoFullscreen"),
    localVideoDiv: document.getElementById("localVideoOnly"),
    localVideoPip: document.getElementById("localVideoPip"),
    localAndRemoteVideoDiv: document.getElementById("localAndRemoteVideo"),
    remoteVideo: document.getElementById("remoteVideo"),
    menu: document.getElementById('menu-btn'),
    settings: document.getElementById('mobile-settings-btn'),
    phone: document.getElementById('cancel-call-btn'),
    mute: document.getElementById('ctrl-mute'),
    controlCam: document.getElementById('ctrl-cam'),
    controlFlip: document.getElementById('ctrl-flip'),
    controlEnd: document.getElementById('ctrl-end'),
    controlSettings: document.getElementById('ctrl-settings'),
    incomingDecline: document.getElementById('inc-decline'),
    incomingAccept: document.getElementById('inc-accept'),
    closeSettings: document.getElementById('close-settings'),
    sidebarOverlay: document.getElementById('close-settings'),
    sidebar: document.getElementById('sidebar'),
    sidebarOvl   : document.getElementById('sidebar-overlay'),
    contactsList : document.getElementById('contacts-list'),
    searchInput  : document.getElementById('search-input'),
    idleScreen   : document.getElementById('idle-screen'),
    callingScr   : document.getElementById('calling-screen'),
    callScreen   : document.getElementById('call-screen'),
    callingAvatar: document.getElementById('calling-avatar'),
    callingName  : document.getElementById('calling-name'),
    remoteArea   : document.getElementById('remote-area'),
    localVideo   : document.getElementById('local-video'),
    pipWrap      : document.getElementById('pip-wrap'),
    pipNoCam     : document.getElementById('pip-no-cam'),
    infoName     : document.getElementById('info-name'),
    infoTimer    : document.getElementById('info-timer'),
    incomingEl   : document.getElementById('incoming-call'),
    incAvatar    : document.getElementById('inc-avatar'),
    incName      : document.getElementById('inc-name'),
    settingsPanel: document.getElementById('settings-panel'),
    addModal     : document.getElementById('add-modal'),
};
