export const elements = {
    idText: document.getElementById("IdDisplay"),
    callInput: document.getElementById("callInput"),
    callButton: document.getElementById("callButton"),
    incomingCallDiv: document.getElementById("incomingCall"),
    incomingCallText: document.getElementById("incomingCaller"),
    incomingCallAcceptButton: document.getElementById("acceptCall"),
    incomingCallDeclineButton: document.getElementById("declineCall"),
    localVideoFullscreen: document.getElementById("localVideoFullscreen"),
    localVideoDiv: document.getElementById("localVideoOnly"),
    localVideoPip: document.getElementById("localVideoPip"),
    localAndRemoteVideoDiv: document.getElementById("localAndRemoteVideo"),
    remoteVideo: document.getElementById("remoteVideo"),
    menu: document.getElementById('menu-btn'),
    settings: document.getElementById('mobile-settings-btn'),
    phone: document.getElementById('cancel-call-btn'),
    mute: document.getElementById('ctrl-mute'),
    controlCam: document.getElementById('ctrl-cam'),
    controlFlip: document.getElementById('ctrl-flip'),
    controlEnd: document.getElementById('ctrl-end'),
    controlSettings: document.getElementById('ctrl-settings'),
    incomingDecline: document.getElementById('inc-decline'),
    incomingAccept: document.getElementById('inc-accept'),
    closeSettings: document.getElementById('close-settings')
};
